/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : task_template_list.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Version     : Component 01.093, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-03-14, 18:22, # CodeGen: 58
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#ifndef __task_template_list_h__
#define __task_template_list_h__

/* MQX Lite task IDs */
#define TASK_DEFAULT_TASK    1U
#define TASK_DAC_TASK        2U

/* MQX Lite task stack sizes */
#define TASK_DEFAULT_TASK_STACK_SIZE (sizeof(TD_STRUCT) + 1024 + PSP_STACK_ALIGNMENT + 1)
#define TASK_DAC_TASK_STACK_SIZE (sizeof(TD_STRUCT) + 2048 + PSP_STACK_ALIGNMENT + 1)


#endif /* __task_template_list_h__ */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
